### ISSUE TITLE
bagit-python is not compatible with Python 3.12 or newer

### ISSUE THREAD

**Issue by sevein** [LibraryOfCongress/bagit-python#180] opened 2024-10-12 10:47 UTC
The commit 44f21392604e3930af9f0b6f9f0937ea3d56fe2e (by @kba and @nkrabben) is an important fix in the master branch that ensures compatibility with Python 3.12 and newer. However, this commit has not been included yet in any release.

To summarize the issue addressed by this commit: pkg_resources was moved to setuptools, but setuptools is no longer included by default in virtual environments. Many projects may not encounter this problem if they have a dependency on setuptools (e.g., installing gevent pulls it in), but for those that don’t, this project becomes unusable in Python 3.12+ environments.

Could a new v1.8.2 release be made to address this problem? Thank you.

Related: https://github.com/LibraryOfCongress/bagit-python/issues/176.

**Comment by acdha** [comment] 2024-10-15 13:00
Closing as a duplicate of #176

**Closed** 2024-10-15 12:59 UTC
